language: nodejs
services:
- docker
before_script:
- docker-compose build client
script:
- docker-compose run client npm run build --prod
deploy:
  provider: s3
  access_key_id: AKIAI2HJ6CE2XNBNALXQ
  secret_access_key: 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
  bucket: opioid-mat
  local_dir: client/dist/client
  skip_cleanup: true
  acl: public_read
