language: nodejs
services:
- docker
before_script:
- openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in gcloud.json.enc -out gcloud.json -d
- docker-compose build client server
script:
- docker-compose run client npm run build --prod
