language: nodejs
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_573b663b7507_key -iv $encrypted_573b663b7507_iv -in credentials.tar.enc -out credentials.tar -d
- tar xvf credentials.tar
install:
- sudo apt-get update -y
- sudo apt-get install --only-upgrade docker -y
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
- sudo apt-get install kubectl
- gcloud auth activate-service-account --key-file=credentials/gcloud.json
- gcloud auth configure-docker -q
- gcloud config set project ${GCLOUD_PROJECT_ID}
- gcloud container clusters get-credentials ${GCLOUD_CLUSTER_NAME} --region=${GCLOUD_PROJECT_REGION}
before_script:
- docker-compose build client
script:
- docker-compose run client npm run build --prod
after_success:
# Upload static files to bucket
- docker-compose run server python manage.py collectstatic
# Update server
- cp credentials/.env-production server/.env
- docker-compose build server
- docker tag opioid-mat-decision-aid_server gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-server
- docker push gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-server
- docker-compose run server-gcloud python manage.py migrate
# Redeploy kubernetes
- sed -i "s/DEFAULT_BUILD_NUMBER/'$TRAVIS_BUILD_NUMBER'/g" deployment.yaml
- kubectl apply -f deployment.yaml
