language: nodejs
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_573b663b7507_key -iv $encrypted_573b663b7507_iv -in credentials.tar.enc -out credentials.tar -d
- tar xvf credentials.tar
install:
# Update docker, because travis might have stale version
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
# Install gcloud tools
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
- sudo apt-get install kubectl
# Set credentials for docker/kubernetes
- gcloud auth activate-service-account --key-file=credentials/gcloud-travis.json
- gcloud auth configure-docker -q
- gcloud config set project ${GCLOUD_PROJECT_ID}
- gcloud container clusters get-credentials ${GCLOUD_CLUSTER_NAME} --region=${GCLOUD_PROJECT_REGION}
before_script:
- docker-compose build server
- docker-compose build client
script:
- docker-compose run server python manage.py test
- docker-compose run client npm run build --prod
after_success:
# Upload static files to bucket
- docker-compose run server python manage.py collectstatic
- gsutil -m rsync -d -r server/static/ gs://opioid-mat-static/static
# Upload website files to bucket
- docker-compose run client npm run build --prod
- gsutil -m rsync -d -r client/dist/client gs://opioid-mat-static/website
# Update nginx
- docker-compose build nginx
- docker tag opioid-mat-nginx gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-nginx
- docker push gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-nginx
# Update server
- cp credentials/.env-production server/.env
- docker-compose build server
- docker tag opioid-mat-server gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-server
- docker push gcr.io/${GCLOUD_PROJECT_ID}/opioid-mat-server
- docker-compose run server-gcloud python manage.py migrate
# Redeploy kubernetes
- sed -i "s/DEFAULT_BUILD_NUMBER/'$TRAVIS_BUILD_NUMBER'/g" deployment.yaml
- kubectl apply -f deployment.yaml
