language: nodejs
services:
- docker
before_script:
- docker-compose build client
script:
- docker-compose run client npm run build --prod
deploy:
  provider: s3
  access_key_id: $s3KeyId
  secret_access_key: $s3AccessKey
  bucket: $s3Bucket
  local_dir: client/dist/client
  skip_cleanup: true
  acl: public_read
