language: nodejs

services:
  - docker

before_script:
  - docker-compose build client

script:
  - docker-compose run client npm build --prod

deploy:
  provider: s3
  access_key_id: AKIAJFLFKTTFVASJZ27A
  secret_access_key:
    secure: gvFCtqNKzwZA+so/AblDFnpUjsEP6oOZ1L+RHjHP2l7jR7TC9Hs47CJMgTyZzMr6bRcqZSfuLMx2Z96eqaK4dtOJf4wZ5DJz+5j3keAeeJ1V3pcBQ3SkCIal3F9IxOvN8MfrAQOILdhx5E/s+FVY1LoLJ5VBP9FdIep0lrpRSshhGTX63cxkAM+Ol8EKuOgmgzdHWr/L1QqEgnrICTV1HiBPUEzDDRmraGQj92ZMqkBapJB1PlAZzpn8PoUBAFukgDl5zv7c/lwgWPCfVDZiFaurGL+aDeTrZpqP35J/g4ifp50XUTTz21/lMH3xjILbCCJpCEJtLuqHhiXcBCHr6FJH+D+h1QilnyYK44PwwGBZLENauUlUGfA3ytpEGgkJSNjeVMZbC41Jet6mrpF7ZRKKuyklGofKpsuBI4kyPYYYjtxrWh5EyMmRBffXLBR8wAihXIDnzp5CCeneYFdAtyNxeh6VQBGl8W5TXPr7ITXbfLSfRgSbvMTMUoqV0pb7eJ1R/+QR2uTDZTglVVv37ZMqjwExPZDRtGY/l+SERDQCvnHU0YazDuUPo9Opm32WCJRYM72GXeFU2mlNc/EcOoBBFXS+dTlkty5MQ7x+7a0rqA8LUTpbRGL3CB93cbR22MZWvJoWEw1tmaddMFep+FNT01WGpubmsRuUJMDfado=
  bucket: opioid-mat
  skip_cleanup: true
  local_dir: client/dist
