version: '2'
services:
    client:
        build: ./client
        command: npm run start
        depends_on:
            - db
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 4200:4200
        volumes:
            - ./client:/client
            - client-node-modules:/client/node_modules
    db:
        environment: 
            - POSTGRES_HOST_AUTH_METHOD=trust
        image: postgres:12.2
        volumes:
            - db-pgdata:/var/lib/postgresql/data
    server:
        build: ./server
        command: honcho start dev
        depends_on:
            - db
        environment:
            - ALLOWED_HOSTS=localhost,server,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://postgres@db:5432/postgres
            - MEDIA_URL=http://localhost:8080/media/
            - PORT=8080
        image: opioid-mat-server
        ports:
            - 8080:8080
        volumes:
            - ./server:/server
volumes:
  db-pgdata:
  client-node-modules:
