version: '2'
services:
    client:
        build: ./client
        command: ng serve --host 0.0.0.0
        depends_on:
            - db
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 4200:4200
        volumes:
            - ./client:/client
            - client-node-modules:/client/node_modules
    db:
        image: postgres
        volumes:
            - db-pgdata:/var/lib/postgresql/data
    server:
        build: ./server
        command: honcho start dev
        depends_on:
            - db
        environment:
            - ALLOWED_HOSTS=localhost,server,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://postgres@db:5432/postgres
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
volumes:
  client-node-modules:
  db-pgdata:
