version: '2'
services:
    client:
        build: ./client
        command: ng serve --host 0.0.0.0
        depends_on:
            - db
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 4200:4200
        volumes:
            - ./client:/client
            - client-node-modules:/client/node_modules
    db:
        image: postgres
        volumes:
            - db-pgdata:/var/lib/postgresql/data
    cloudsql:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command:  /cloud_sql_proxy -instances=opioid-mat:us-west1:opioid-mat=tcp:0.0.0.0:5432 -credential_file=/gcloud.json
        volumes:
            - ./gcloud.json:/gcloud.json
    server:
        build: ./server
        command: honcho start dev
        depends_on:
            - db
        environment:
            - ALLOWED_HOSTS=localhost,server,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://postgres@db:5432/postgres
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
    server-gcloud:
        image: opioid-mat-decision-aid_server
        depends_on:
            - cloudsql
        env_file: .env-production
        environment:
            - ALLOWED_HOSTS=localhost,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://opioid-mat:opioid-mat@cloudsql:5432/opioid-mat
        ports:
            - 8000:8000
        volumes:
            - ./server:/server
volumes:
  client-node-modules:
  db-pgdata:
