version: '2'
services:
    client:
        build: ./client
        command: npm run start
        depends_on:
            - db
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
        ports:
            - 4200:4200
        volumes:
            - ./client:/client
            - client-node-modules:/client/node_modules
    db:
        image: postgres
        volumes:
            - db-pgdata:/var/lib/postgresql/data
    cloudsql:
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command:  /cloud_sql_proxy -instances=opioid-mat:us-west1:opioid-mat=tcp:0.0.0.0:5432 -credential_file=/gcloud.json
        volumes:
            - ./credentials/gcloud.json:/gcloud.json
    nginx:
        build: ./nginx
        image: opioid-mat-nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "8000:8000"
        depends_on:
            - server
    server:
        build: ./server
        command: honcho start dev
        depends_on:
            - db
        environment:
            - ALLOWED_HOSTS=localhost,server,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://postgres@db:5432/postgres
            - MEDIA_URL=http://localhost:8080/media/
        image: opioid-mat-server
        ports:
            - 8080:8080
        volumes:
            - ./server:/server
    server-gcloud:
        image: opioid-mat-server
        depends_on:
            - cloudsql
        env_file: credentials/.env-production
        environment:
            - ALLOWED_HOSTS=localhost,192.168.99.100
            - DEBUG=True
            - DATABASE_URL=psql://opioid-mat:opioid-mat@cloudsql:5432/opioid-mat
        ports:
            - 8080:8080
        volumes:
            - ./server:/server
volumes:
  client-node-modules:
  db-pgdata:
