# Generated by Django 2.2.1 on 2019-06-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication_icons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationEffectIcon',
        ),
    ]
