# Generated by Django 2.2.1 on 2019-06-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication_icons', '0002_delete_medicationeffecticon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['name']},
        ),
    ]
