# Generated by Django 2.2.1 on 2019-05-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Chart')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='medications.Medication')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChartEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charts.Chart')),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='medications.Effect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
