# Generated by Django 2.2.1 on 2019-06-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_charteffect_chartmedication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charteffect',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='chartmedication',
            options={'ordering': ['order']},
        ),
    ]
