# Generated by Django 2.2.1 on 2019-08-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20190619_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='points_to_pass',
        ),
    ]
