# Generated by Django 2.2.1 on 2019-05-13 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
    ]
