# Generated by Django 2.2.1 on 2019-05-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_auto_20190513_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
