# Generated by Django 2.2.1 on 2019-05-15 18:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_auto_20190513_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
