# Generated by Django 2.2.1 on 2019-05-15 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_charteffect_chartmedication'),
        ('chapters', '0004_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charts.Chart'),
        ),
    ]
