# Generated by Django 2.2.1 on 2019-08-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_quiz_points_to_pass'),
        ('chapters', '0007_auto_20190622_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chapters.Page')),
                ('test_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chapters.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PageRedirectTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_to_pass', models.PositiveIntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quizes.Quiz')),
                ('redirect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chapters.PageRedirect')),
            ],
        ),
    ]
