# Generated by Django 2.2.1 on 2019-08-07 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_remove_quiz_points_to_pass'),
        ('chapters', '0008_pageredirect_pageredirecttest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageRedirectTest',
            new_name='PageRedirectCondition',
        ),
    ]
