# Generated by Django 2.2.1 on 2020-09-20 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0012_orderablecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderablecontent',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='orderablecontent',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
