# Generated by Django 2.2.1 on 2020-09-20 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_auto_20200920_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderablecontent',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderablecontent',
            name='object_id',
        ),
    ]
