# Generated by Django 2.2.1 on 2019-06-09 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicationeffect',
            old_name='short_description',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='medicationeffect',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effects', to='medications.Medication'),
        ),
    ]
