# Generated by Django 2.2.1 on 2019-06-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20190609_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationeffect',
            name='description',
        ),
        migrations.AddField(
            model_name='medicationeffect',
            name='day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationeffect',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
