# Generated by Django 2.2.1 on 2019-06-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_auto_20190610_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationeffect',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
