# Generated by Django 2.2.1 on 2019-06-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medicationeffect_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicationeffect',
            options={'ordering': ['day', 'order']},
        ),
    ]
