# Generated by Django 2.2.1 on 2019-06-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_auto_20190610_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationeffect',
            name='comparison',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
