# Generated by Django 2.2.1 on 2019-06-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0006_medicationeffect_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
