# Generated by Django 2.2.1 on 2019-06-10 19:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0007_effect_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='effect',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='effect',
            name='category',
            field=models.CharField(blank=True, choices=[('circle', 'Circle chart'), ('icon', 'Icon'), ('list', 'List of values'), ('timeline', 'Timeline of values')], max_length=250, null=True),
        ),
    ]
