# Generated by Django 2.2.1 on 2019-06-24 05:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0009_medicationeffect_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effect',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicationeffect',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medication_icons.Icon'),
        ),
    ]
